name: Main CI-pipeline

on:
  push:
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y valgrind gcc make clang-format

      - name: Check code style
        run: make check_fmt

      - name: Build and run all tests
        run: make test
